name: CI
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile
      
      - name: try building
        run: npm run build
      
  sandbox-deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/nuxt3-hot'
    steps:
      - name: Clean Git Repository
        run:
          git clean -X -n --exclude="!node_modules" &&
          git reset --hard HEAD
        continue-on-error: true

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
        # My poor raspberry pi needs to survive. No more disk stuff
         clean: false
         
      - name: Set node version
        run: alias node='n use auto'

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: generate static files
        run: npm run generate

